### ISSUE TITLE
Upgrade of this package

### ISSUE THREAD

**Issue by Teo-ShaoWei** [AndreyKolev/GARCH.jl#4]
@AndreyKolev I see this package listed in Julia's METADATA and decided to drop in for a look.  I am interested to contribute to the program.  Would you be ok with that?

**Comment by AndreyKolev** [comment]
Hi! Of course I'm ok with that, also please notice that I've copied all
code to the TimeModels package (https://github.com/JuliaStats/TimeModels.jl).
It covers more broad time series models functionality, and is considered to
be the main repo for varius ts-related code, so you could also consider
contributing to it.

2015-10-14 11:55 GMT+03:00 ShaoWei Teo <notifications@github.com>:

**Comment by Teo-ShaoWei** [comment]
Hi its great to hear from you!

Yes I found the TimeModels package and realized your code is inside there too.  Should I directly suggest pull request to there instead?  Would want to keep one source for me else things get confusing.

Also, is there plan to move towards Julia v0.4?  I realized that both packages are currently using v0.3 constructs.

**Comment by AndreyKolev** [comment]
Sorry for delay! Yes, I think TimeModel is a better place for all
time-series related stuff, so you can go on with a pull request.
Don't know about v0.4  though, but anyways with the 8 contributors it's
more easy to support the package and up-to-date Julia versions.


2015-10-14 14:05 GMT+03:00 ShaoWei Teo <notifications@github.com>:

**Comment by Teo-ShaoWei** [comment]
Ah ok, sincere thanks for the suggestion, I will throw do a pull request there then.

Good job on the program by the way, I see it was a 2012 effort when Julia was still very new and things are very experimental.
